workflows:
  cordova-release-workflow:
    name: Cordova Android Release Build
    max_build_duration: 30

    environment:
      node: latest
      vars:
        KEYSTORE_PATH: dccarlobos-key.jks
        KEYSTORE_PASSWORD: 143143
        KEY_ALIAS: ilovemoney
        KEY_PASSWORD: 143143

    scripts:
      # 1️⃣ Install Cordova
      - name: Install Cordova
        script: |
          npm install -g cordova@12

      # 2️⃣ Clean plugins
      - name: Clean Plugins
        script: |
          cordova plugin remove cordova-plugin-x-socialsharing || true
          cordova plugin remove cordova-plugin-inappbrowser || true
          cordova plugin remove cordova-plugin-statusbar || true
          cordova plugin remove cordova-plugin-splashscreen || true
          cordova plugin remove cordova-plugin-network-information || true
          cordova plugin remove cordova-plugin-admob-plus || true

      # 3️⃣ Install plugins (stable)
      - name: Install Plugins
        script: |
          cordova plugin add cordova-plugin-x-socialsharing@6.0.4
          cordova plugin add cordova-plugin-inappbrowser@5.0.0
          cordova plugin add cordova-plugin-statusbar@4.0.0
          cordova plugin add cordova-plugin-splashscreen@6.0.2
          cordova plugin add cordova-plugin-network-information@2.0.2
          cordova plugin add cordova-plugin-admob-plus@1.3.2

      # 4️⃣ Re-add Android platform (PINNED!)
      - name: Add Android Platform (Stable)
        script: |
          cordova platform rm android || true
          cordova platform add android@13.0.0
          cordova prepare android

      # 5️⃣ Verify keystore
      - name: Verify Keystore
        script: |
          ls -l $KEYSTORE_PATH || (echo "❌ Keystore not found!" && exit 1)

      # 6️⃣ Fix android:exported issue
      - name: Patch AndroidManifest
        script: |
          sed -i 's/<receiver android:name="nl.xservices.plugins.ShareChooserPendingIntent"/<receiver android:name="nl.xservices.plugins.ShareChooserPendingIntent" android:exported="true"/' platforms/android/app/src/main/AndroidManifest.xml || true

      # 7️⃣ Build signed APK
      - name: Build Signed APK
        script: |
          cordova build android --release \
            -- --packageType=apk \
               --keystore=$KEYSTORE_PATH \
               --storePassword=$KEYSTORE_PASSWORD \
               --alias=$KEY_ALIAS \
               --password=$KEY_PASSWORD

      # 8️⃣ Build signed AAB
      - name: Build Signed AAB
        script: |
          cordova build android --release \
            -- --packageType=bundle \
               --keystore=$KEYSTORE_PATH \
               --storePassword=$KEYSTORE_PASSWORD \
               --alias=$KEY_ALIAS \
               --password=$KEY_PASSWORD

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/*.aab