workflows:
  cordova-release-workflow:
    name: Cordova Android Release Build
    max_build_duration: 30
    environment:
      node: latest
      vars:
        CORDOVA_PLATFORM: android
        KEYSTORE_PATH: dccarlobos-key.jks
        KEYSTORE_PASSWORD: 143143
        KEY_ALIAS: ilovemoney
        KEY_PASSWORD: 143143

    scripts:
      - name: Install Cordova
        script: npm install -g cordova

      - name: Install Plugins
        script: |
          echo "🔧 Removing old plugins..."
          cordova plugin remove cordova-plugin-x-socialsharing || true
          cordova plugin remove cordova-plugin-splashscreen || true
          cordova plugin remove cordova-plugin-inappbrowser || true
          cordova plugin remove cordova-plugin-android-fullscreen || true
          cordova plugin remove cordova-plugin-network-information || true

          echo "📦 Installing plugins..."
          cordova plugin add cordova-plugin-x-socialsharing-android12@6.0.5
          cordova plugin add cordova-plugin-inappbrowser
          cordova plugin add cordova-plugin-splashscreen
          cordova plugin add cordova-plugin-android-fullscreen
          cordova plugin add cordova-plugin-network-information

      - name: Clean and Re-add Android Platform
        script: |
          echo "🧹 Cleaning and re-adding Android platform..."
          cordova platform rm android || true
          cordova platform add android
          cordova prepare android

      - name: Verify Keystore
        script: |
          echo "🔐 Checking if keystore file exists..."
          ls -l $KEYSTORE_PATH || (echo "❌ Keystore not found!" && exit 1)

      - name: Patch AndroidManifest (android:exported fix)
        script: |
          echo "🩹 Patching AndroidManifest.xml..."
          sed -i 's/<receiver android:name="nl.xservices.plugins.ShareChooserPendingIntent"/<receiver android:name="nl.xservices.plugins.ShareChooserPendingIntent" android:exported="true"/' platforms/android/app/src/main/AndroidManifest.xml || true

      - name: Build Signed Release APK
        script: |
          echo "🏗️ Building signed release APK..."
          cordova build android --release \
            -- --packageType=apk \
               --keystore=$KEYSTORE_PATH \
               --storePassword=$KEYSTORE_PASSWORD \
               --alias=$KEY_ALIAS \
               --password=$KEY_PASSWORD

      - name: Build Signed Release AAB
        script: |
          echo "🏗️ Building signed release AAB..."
          cordova build android --release \
            -- --packageType=bundle \
               --keystore=$KEYSTORE_PATH \
               --storePassword=$KEYSTORE_PASSWORD \
               --alias=$KEY_ALIAS \
               --password=$KEY_PASSWORD

      - name: Debug Output Paths
        script: |
          echo "📁 Listing possible build output directories..."
          ls -R platforms/android/app/build/outputs || echo "⚠️ No outputs found."

      - name: Verify Build Files
        script: |
          echo "✅ Checking if APK or AAB files exist..."
          find platforms/android/app/build/outputs -type f \( -name "*.apk" -o -name "*.aab" \) || echo "❌ No build outputs found!"

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/*.aab