workflows:
  cordova-workflow:
    name: Cordova Android Build
    max_build_duration: 30
    environment:
      node: latest
      vars:
        CORDOVA_PLATFORM: android
    scripts:
      - name: Install Cordova
        script: npm install -g cordova

      - name: Install Plugins
        script: |
          cordova plugin add cordova-plugin-x-socialsharing || true
          cordova plugin add cordova-plugin-inappbrowser || true

      - name: Remove Android Platform (Clean)
        script: cordova platform rm android || true

      - name: Add Android Platform
        script: cordova platform add android

      - name: Prepare Android
        script: cordova prepare android

      - name: Patch AndroidManifest (android:exported)
        script: |
          FILE="platforms/android/app/src/main/AndroidManifest.xml"
          if grep -q 'nl.xservices.plugins.ShareChooserPendingIntent' "$FILE"; then
            echo "Patching AndroidManifest.xml..."
            sed -i.bak 's/<receiver android:name="nl.xservices.plugins.ShareChooserPendingIntent"/<receiver android:name="nl.xservices.plugins.ShareChooserPendingIntent" android:exported="true"/' "$FILE"
          else
            echo "No patch needed."
          fi

      - name: Build APK (Debug)
        script: cordova build android --debug

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk