workflows:
  cordova-workflow:
    name: Cordova Android Build
    max_build_duration: 30
    environment:
      node: latest
      vars:
        CORDOVA_PLATFORM: android
    scripts:
      - name: Install Cordova
        script: npm install -g cordova

      - name: Install Splashscreen Plugin
        script: cordova plugin add cordova-plugin-splashscreen || true

      - name: Add Android platform
        script: cordova platform add android || true

      - name: Prepare Android
        script: cordova prepare android

      - name: Build APK (Debug)
        script: cordova build android --debug

      # Optional: Release build
      #- name: Build APK (Release)
      #  script: cordova build android --release

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk