workflows:
  cordova-release-workflow:
    name: Cordova Android Release Build
    max_build_duration: 30
    environment:
      node: latest
      vars:
        CORDOVA_PLATFORM: android
        KEYSTORE_PATH: dccarlobos-key.jks
        KEYSTORE_PASSWORD: 143143
        KEY_ALIAS: ilovemoney
        KEY_PASSWORD: 143143
    scripts:
      - name: Install Cordova
        script: npm install -g cordova

      - name: Install Plugins
        script: |
          # tanggalin luma kung meron
          cordova plugin remove cordova-plugin-x-socialsharing || true
          cordova plugin remove cordova-plugin-splashscreen || true

          # install bagong plugin
          cordova plugin add cordova-plugin-x-socialsharing-android12@6.0.5 || true
          cordova plugin add cordova-plugin-inappbrowser || true
          cordova plugin add cordova-plugin-splashscreen || true

      - name: Clean Android Platform
        script: cordova platform rm android || true

      - name: Add Android Platform
        script: cordova platform add android

      - name: Prepare Android
        script: cordova prepare android

      - name: Patch AndroidManifest (android:exported fix)
        script: |
          sed -i 's/<receiver android:name="nl.xservices.plugins.ShareChooserPendingIntent"/<receiver android:name="nl.xservices.plugins.ShareChooserPendingIntent" android:exported="true"/' platforms/android/app/src/main/AndroidManifest.xml || true

      - name: Build Signed Release APK
        script: |
          cordova build android --release \
          -- --keystore=$KEYSTORE_PATH \
             --storePassword=$KEYSTORE_PASSWORD \
             --alias=$KEY_ALIAS \
             --password=$KEY_PASSWORD

      - name: Build Signed AAB (App Bundle)
        script: |
          cd platforms/android
          ./gradlew bundleRelease -PcdvBuildMultipleApks=false \
            -PcdvReleaseSigningPropertiesFile=../../$KEYSTORE_PATH \
            -PcdvStorePassword=$KEYSTORE_PASSWORD \
            -PcdvKeyAlias=$KEY_ALIAS \
            -PcdvKeyPassword=$KEY_PASSWORD
          cd ../../

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/*.aab