workflows:
  cordova-workflow:
    name: Cordova Android Build
    max_build_duration: 30
    environment:
      node: latest
      groups:
        - signing # dito naka-save yung keystore at passwords
    scripts:
      - name: Install Cordova
        script: npm install -g cordova

      - name: Install Plugins
        script: |
          cordova plugin remove cordova-plugin-x-socialsharing || true
          cordova plugin add cordova-plugin-x-socialsharing
          cordova plugin add cordova-plugin-inappbrowser
          cordova plugin add cordova-plugin-splashscreen
          cordova plugin add cordova-plugin-network-information

      - name: Remove Android Platform (Clean)
        script: cordova platform remove android || true

      - name: Add Android Platform
        script: cordova platform add android

      - name: Prepare Android
        script: cordova prepare android

      - name: Patch AndroidManifest (safety for android:exported)
        script: |
          sed -i.bak 's/android:exported="false"/android:exported="true"/g' platforms/android/app/src/main/AndroidManifest.xml || true

      - name: Build APK (Release)
        script: |
          cordova build android --release \
            -- --keystore=$CM_KEYSTORE_PATH \
               --storePassword=$CM_KEYSTORE_PASSWORD \
               --alias=$CM_KEY_ALIAS \
               --password=$CM_KEY_PASSWORD

      - name: Build AAB (Release)
        script: |
          cordova build android --release -- --packageType=bundle \
            -- --keystore=$CM_KEYSTORE_PATH \
               --storePassword=$CM_KEYSTORE_PASSWORD \
               --alias=$CM_KEY_ALIAS \
               --password=$CM_KEY_PASSWORD

      - name: List build outputs
        script: |
          echo "APK and AAB outputs:"
          ls -lh platforms/android/app/build/outputs/*/* || true

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
      - platforms/android/app/build/outputs/bundle/release/*.aab