workflows:
  cordova-workflow:
    name: Cordova Android Build
    max_build_duration: 30
    environment:
      vars:
        CORDOVA_PLATFORM: android
      node: latest
    scripts:
      - name: Install Cordova
        script: npm install -g cordova
      - name: Add Android platform
        script: cordova platform add android
      - name: Build APK
        script: cordova build android --debug
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk